import Head from "next/head";
import * as Style from "./styles";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Style.SectionOne>
          <div>
            <p>Bem vindo</p>
          </div>
        </Style.SectionOne>
      </main>
    </div>
  );
}
